version: '3'
services:
    posts:
        build:
            context: posts-service
            dockerfile: dev.Dockerfile
        image: posts-service
        restart: on-failure
        ports:
            - 3000:3000
        volumes:
            - ./posts-service/src:/app/src
    
    users:
        build:
            context: users-service
            dockerfile: dev.Dockerfile
        image: users-service
        restart: on-failure
        ports:
            - 3001:3000
        volumes:
            - ./users-service/src:/app/src